{% set name = "datasette-dashboards" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datasette_dashboards-{{ version }}.tar.gz
  sha256: 41779fae786c2d0969cb3bebdab58e819def8ccb80c3519a8c8201a7caee9c21

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0.0
    - datasette
    - datasette-leaflet
    - datasette-render-markdown

test:
  imports:
    - datasette_dashboards
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rclement/datasette-dashboards
  summary: Datasette plugin providing data dashboards from metadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
